/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import dominio.Autor;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import persistencia.AutoresDAO;
/**
 *
 * @author emiliano
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupBuscarLibros = new javax.swing.ButtonGroup();
        buttonGroupBuscarAutor = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelPrestamos = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelAfiliados = new javax.swing.JPanel();
        panelLibros = new javax.swing.JPanel();
        librosNuevo = new javax.swing.JButton();
        librosBuscar = new javax.swing.JButton();
        librosModificar = new javax.swing.JButton();
        librosEliminar = new javax.swing.JButton();
        cardLayoutCamposLibros = new javax.swing.JPanel();
        subPanelNuevoLibros = new javax.swing.JPanel();
        subPanelModificarLibros = new javax.swing.JPanel();
        subPanelEliminarLibros = new javax.swing.JPanel();
        subPanelBuscarLibros = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        textoBuscarLibros = new javax.swing.JTextField();
        buttonBuscarLibros = new javax.swing.JButton();
        cardLayoutTablaLibros = new javax.swing.JPanel();
        subPanelBuscarTablaLibros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        subPanelModificarTablaLibros = new javax.swing.JPanel();
        subPanelEliminarTablaLibros = new javax.swing.JPanel();
        subPanelNuevoTablaLibros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        panelAutores = new javax.swing.JPanel();
        autorNuevo = new javax.swing.JButton();
        autorBuscar = new javax.swing.JButton();
        autorModificar = new javax.swing.JButton();
        autorEliminar = new javax.swing.JButton();
        cardLayoutCamposAutor = new javax.swing.JPanel();
        subPanelNuevoAutor = new javax.swing.JPanel();
        subPanelModificarAutor = new javax.swing.JPanel();
        subPanelEliminarAutor = new javax.swing.JPanel();
        subPanelBuscarAutor = new javax.swing.JPanel();
        radioNombreBuscarAutor = new javax.swing.JRadioButton();
        radioApellidoBuscarAutor = new javax.swing.JRadioButton();
        radioNacionalidadBuscarAutor = new javax.swing.JRadioButton();
        textoBuscarAutor = new javax.swing.JTextField();
        buttonBuscarAutor = new javax.swing.JButton();
        cardLayoutTablaAutor = new javax.swing.JPanel();
        subPanelBuscarTablaAutor = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBuscarAutor = new javax.swing.JTable();
        subPanelModificarTablaAutor = new javax.swing.JPanel();
        subPanelEliminarTablaAutor = new javax.swing.JPanel();
        subPanelNuevoTablaAutor = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        panelEditoriales = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");

        jButton3.setText("Buscar");

        jButton4.setText("Eliminar");

        javax.swing.GroupLayout panelPrestamosLayout = new javax.swing.GroupLayout(panelPrestamos);
        panelPrestamos.setLayout(panelPrestamosLayout);
        panelPrestamosLayout.setHorizontalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1016, Short.MAX_VALUE))
        );
        panelPrestamosLayout.setVerticalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(483, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prestamos", panelPrestamos);

        javax.swing.GroupLayout panelAfiliadosLayout = new javax.swing.GroupLayout(panelAfiliados);
        panelAfiliados.setLayout(panelAfiliadosLayout);
        panelAfiliadosLayout.setHorizontalGroup(
            panelAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1108, Short.MAX_VALUE)
        );
        panelAfiliadosLayout.setVerticalGroup(
            panelAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Afiliados", panelAfiliados);

        librosNuevo.setText("Nuevo");
        librosNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosNuevoActionPerformed(evt);
            }
        });

        librosBuscar.setText("Buscar");
        librosBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosBuscarActionPerformed(evt);
            }
        });

        librosModificar.setText("Modificar");
        librosModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosModificarActionPerformed(evt);
            }
        });

        librosEliminar.setText("Eliminar");
        librosEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosEliminarActionPerformed(evt);
            }
        });

        cardLayoutCamposLibros.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout subPanelNuevoLibrosLayout = new javax.swing.GroupLayout(subPanelNuevoLibros);
        subPanelNuevoLibros.setLayout(subPanelNuevoLibrosLayout);
        subPanelNuevoLibrosLayout.setHorizontalGroup(
            subPanelNuevoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        subPanelNuevoLibrosLayout.setVerticalGroup(
            subPanelNuevoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        cardLayoutCamposLibros.add(subPanelNuevoLibros, "cardNuevoLibros");

        javax.swing.GroupLayout subPanelModificarLibrosLayout = new javax.swing.GroupLayout(subPanelModificarLibros);
        subPanelModificarLibros.setLayout(subPanelModificarLibrosLayout);
        subPanelModificarLibrosLayout.setHorizontalGroup(
            subPanelModificarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        subPanelModificarLibrosLayout.setVerticalGroup(
            subPanelModificarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        cardLayoutCamposLibros.add(subPanelModificarLibros, "cardModificarLibros");

        javax.swing.GroupLayout subPanelEliminarLibrosLayout = new javax.swing.GroupLayout(subPanelEliminarLibros);
        subPanelEliminarLibros.setLayout(subPanelEliminarLibrosLayout);
        subPanelEliminarLibrosLayout.setHorizontalGroup(
            subPanelEliminarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        subPanelEliminarLibrosLayout.setVerticalGroup(
            subPanelEliminarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        cardLayoutCamposLibros.add(subPanelEliminarLibros, "cardEliminarLibros");

        subPanelBuscarLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroupBuscarLibros.add(jRadioButton1);
        jRadioButton1.setText("Título");

        buttonGroupBuscarLibros.add(jRadioButton2);
        jRadioButton2.setText("ISBN");

        buttonGroupBuscarLibros.add(jRadioButton3);
        jRadioButton3.setText("Autor");

        textoBuscarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoBuscarLibrosActionPerformed(evt);
            }
        });

        buttonBuscarLibros.setText("jButton5");

        javax.swing.GroupLayout subPanelBuscarLibrosLayout = new javax.swing.GroupLayout(subPanelBuscarLibros);
        subPanelBuscarLibros.setLayout(subPanelBuscarLibrosLayout);
        subPanelBuscarLibrosLayout.setHorizontalGroup(
            subPanelBuscarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelBuscarLibrosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(subPanelBuscarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addGroup(subPanelBuscarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, subPanelBuscarLibrosLayout.createSequentialGroup()
                            .addComponent(jRadioButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonBuscarLibros))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, subPanelBuscarLibrosLayout.createSequentialGroup()
                            .addComponent(jRadioButton2)
                            .addGap(212, 212, 212)
                            .addComponent(textoBuscarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        subPanelBuscarLibrosLayout.setVerticalGroup(
            subPanelBuscarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelBuscarLibrosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelBuscarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(textoBuscarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelBuscarLibrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBuscarLibros)
                .addContainerGap())
        );

        cardLayoutCamposLibros.add(subPanelBuscarLibros, "cardBuscarLibros");

        cardLayoutTablaLibros.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "Editorial", "Edición", "Páginas", "Dependencia", "Ejemplares", "Año", "Idioma"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Páginas");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Dependencia");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Ejemplares");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("Año");
            jTable1.getColumnModel().getColumn(8).setHeaderValue("Idioma");
        }

        javax.swing.GroupLayout subPanelBuscarTablaLibrosLayout = new javax.swing.GroupLayout(subPanelBuscarTablaLibros);
        subPanelBuscarTablaLibros.setLayout(subPanelBuscarTablaLibrosLayout);
        subPanelBuscarTablaLibrosLayout.setHorizontalGroup(
            subPanelBuscarTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelBuscarTablaLibrosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        subPanelBuscarTablaLibrosLayout.setVerticalGroup(
            subPanelBuscarTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelBuscarTablaLibrosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cardLayoutTablaLibros.add(subPanelBuscarTablaLibros, "cardBuscarTablaLibros");

        javax.swing.GroupLayout subPanelModificarTablaLibrosLayout = new javax.swing.GroupLayout(subPanelModificarTablaLibros);
        subPanelModificarTablaLibros.setLayout(subPanelModificarTablaLibrosLayout);
        subPanelModificarTablaLibrosLayout.setHorizontalGroup(
            subPanelModificarTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        subPanelModificarTablaLibrosLayout.setVerticalGroup(
            subPanelModificarTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        cardLayoutTablaLibros.add(subPanelModificarTablaLibros, "cardModificarTablaLibros");

        javax.swing.GroupLayout subPanelEliminarTablaLibrosLayout = new javax.swing.GroupLayout(subPanelEliminarTablaLibros);
        subPanelEliminarTablaLibros.setLayout(subPanelEliminarTablaLibrosLayout);
        subPanelEliminarTablaLibrosLayout.setHorizontalGroup(
            subPanelEliminarTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        subPanelEliminarTablaLibrosLayout.setVerticalGroup(
            subPanelEliminarTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        cardLayoutTablaLibros.add(subPanelEliminarTablaLibros, "cardEliminarTablaLibros");

        jLabel1.setText("ISBN");

        jLabel2.setText("Título");

        jLabel3.setText("Idioma");

        jLabel4.setText("Género");

        jLabel5.setText("Editorial");

        jLabel6.setText("Páginas");

        jLabel7.setText("Páginas");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField1");

        jTextField3.setText("jTextField1");

        jTextField4.setText("jTextField1");

        jTextField5.setText("jTextField1");

        jTextField6.setText("jTextField1");

        jTextField7.setText("jTextField1");

        jTextField8.setText("jTextField1");

        javax.swing.GroupLayout subPanelNuevoTablaLibrosLayout = new javax.swing.GroupLayout(subPanelNuevoTablaLibros);
        subPanelNuevoTablaLibros.setLayout(subPanelNuevoTablaLibrosLayout);
        subPanelNuevoTablaLibrosLayout.setHorizontalGroup(
            subPanelNuevoTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelNuevoTablaLibrosLayout.createSequentialGroup()
                .addGroup(subPanelNuevoTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelNuevoTablaLibrosLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel7))
                    .addGroup(subPanelNuevoTablaLibrosLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(subPanelNuevoTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(subPanelNuevoTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(647, Short.MAX_VALUE))
        );
        subPanelNuevoTablaLibrosLayout.setVerticalGroup(
            subPanelNuevoTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelNuevoTablaLibrosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(subPanelNuevoTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelNuevoTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelNuevoTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelNuevoTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelNuevoTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelNuevoTablaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardLayoutTablaLibros.add(subPanelNuevoTablaLibros, "cardNuevoTablaLibros");

        javax.swing.GroupLayout panelLibrosLayout = new javax.swing.GroupLayout(panelLibros);
        panelLibros.setLayout(panelLibrosLayout);
        panelLibrosLayout.setHorizontalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardLayoutTablaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelLibrosLayout.createSequentialGroup()
                        .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(librosBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(librosNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(librosEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(librosModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cardLayoutCamposLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLibrosLayout.setVerticalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardLayoutCamposLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLibrosLayout.createSequentialGroup()
                        .addComponent(librosBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(librosNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(librosModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(librosEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardLayoutTablaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Libros", panelLibros);

        autorNuevo.setText("Nuevo");
        autorNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorNuevoActionPerformed(evt);
            }
        });

        autorBuscar.setText("Buscar");
        autorBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorBuscarActionPerformed(evt);
            }
        });

        autorModificar.setText("Modificar");
        autorModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorModificarActionPerformed(evt);
            }
        });

        autorEliminar.setText("Eliminar");
        autorEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorEliminarActionPerformed(evt);
            }
        });

        cardLayoutCamposAutor.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout subPanelNuevoAutorLayout = new javax.swing.GroupLayout(subPanelNuevoAutor);
        subPanelNuevoAutor.setLayout(subPanelNuevoAutorLayout);
        subPanelNuevoAutorLayout.setHorizontalGroup(
            subPanelNuevoAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        subPanelNuevoAutorLayout.setVerticalGroup(
            subPanelNuevoAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        cardLayoutCamposAutor.add(subPanelNuevoAutor, "cardNuevoAutor");

        javax.swing.GroupLayout subPanelModificarAutorLayout = new javax.swing.GroupLayout(subPanelModificarAutor);
        subPanelModificarAutor.setLayout(subPanelModificarAutorLayout);
        subPanelModificarAutorLayout.setHorizontalGroup(
            subPanelModificarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        subPanelModificarAutorLayout.setVerticalGroup(
            subPanelModificarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        cardLayoutCamposAutor.add(subPanelModificarAutor, "cardModificarAutor");

        javax.swing.GroupLayout subPanelEliminarAutorLayout = new javax.swing.GroupLayout(subPanelEliminarAutor);
        subPanelEliminarAutor.setLayout(subPanelEliminarAutorLayout);
        subPanelEliminarAutorLayout.setHorizontalGroup(
            subPanelEliminarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        subPanelEliminarAutorLayout.setVerticalGroup(
            subPanelEliminarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        cardLayoutCamposAutor.add(subPanelEliminarAutor, "cardEliminarAutor");

        subPanelBuscarAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroupBuscarAutor.add(radioNombreBuscarAutor);
        radioNombreBuscarAutor.setSelected(true);
        radioNombreBuscarAutor.setText("Nombre");
        radioNombreBuscarAutor.setActionCommand("nombre");

        buttonGroupBuscarAutor.add(radioApellidoBuscarAutor);
        radioApellidoBuscarAutor.setText("Apellido");
        radioApellidoBuscarAutor.setActionCommand("apellido");
        radioApellidoBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioApellidoBuscarAutorActionPerformed(evt);
            }
        });

        buttonGroupBuscarAutor.add(radioNacionalidadBuscarAutor);
        radioNacionalidadBuscarAutor.setText("Nacionalidad");
        radioNacionalidadBuscarAutor.setActionCommand("nacionalidad");

        textoBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoBuscarAutorActionPerformed(evt);
            }
        });

        buttonBuscarAutor.setText("Buscar");
        buttonBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelBuscarAutorLayout = new javax.swing.GroupLayout(subPanelBuscarAutor);
        subPanelBuscarAutor.setLayout(subPanelBuscarAutorLayout);
        subPanelBuscarAutorLayout.setHorizontalGroup(
            subPanelBuscarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelBuscarAutorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(subPanelBuscarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioNombreBuscarAutor)
                    .addGroup(subPanelBuscarAutorLayout.createSequentialGroup()
                        .addComponent(radioNacionalidadBuscarAutor)
                        .addGap(88, 88, 88)
                        .addComponent(textoBuscarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonBuscarAutor))
                    .addComponent(radioApellidoBuscarAutor))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        subPanelBuscarAutorLayout.setVerticalGroup(
            subPanelBuscarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelBuscarAutorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(radioNombreBuscarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioApellidoBuscarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelBuscarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioNacionalidadBuscarAutor)
                    .addComponent(textoBuscarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarAutor))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        cardLayoutCamposAutor.add(subPanelBuscarAutor, "cardBuscarAutor");

        cardLayoutTablaAutor.setLayout(new java.awt.CardLayout());

        tablaBuscarAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellido", "Nombre", "Nacionalidad", "Fecha de Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaBuscarAutor);

        javax.swing.GroupLayout subPanelBuscarTablaAutorLayout = new javax.swing.GroupLayout(subPanelBuscarTablaAutor);
        subPanelBuscarTablaAutor.setLayout(subPanelBuscarTablaAutorLayout);
        subPanelBuscarTablaAutorLayout.setHorizontalGroup(
            subPanelBuscarTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelBuscarTablaAutorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        subPanelBuscarTablaAutorLayout.setVerticalGroup(
            subPanelBuscarTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelBuscarTablaAutorLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        cardLayoutTablaAutor.add(subPanelBuscarTablaAutor, "cardBuscarTablaAutor");

        javax.swing.GroupLayout subPanelModificarTablaAutorLayout = new javax.swing.GroupLayout(subPanelModificarTablaAutor);
        subPanelModificarTablaAutor.setLayout(subPanelModificarTablaAutorLayout);
        subPanelModificarTablaAutorLayout.setHorizontalGroup(
            subPanelModificarTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        subPanelModificarTablaAutorLayout.setVerticalGroup(
            subPanelModificarTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        cardLayoutTablaAutor.add(subPanelModificarTablaAutor, "cardModificarTablaAutor");

        javax.swing.GroupLayout subPanelEliminarTablaAutorLayout = new javax.swing.GroupLayout(subPanelEliminarTablaAutor);
        subPanelEliminarTablaAutor.setLayout(subPanelEliminarTablaAutorLayout);
        subPanelEliminarTablaAutorLayout.setHorizontalGroup(
            subPanelEliminarTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        subPanelEliminarTablaAutorLayout.setVerticalGroup(
            subPanelEliminarTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        cardLayoutTablaAutor.add(subPanelEliminarTablaAutor, "cardEliminarTablaAutor");

        jLabel8.setText("ISBN");

        jLabel9.setText("Título");

        jLabel10.setText("Idioma");

        jLabel11.setText("Género");

        jLabel12.setText("Editorial");

        jLabel13.setText("Páginas");

        jLabel14.setText("Páginas");

        jTextField9.setText("jTextField1");

        jTextField10.setText("jTextField1");

        jTextField11.setText("jTextField1");

        jTextField12.setText("jTextField1");

        jTextField13.setText("jTextField1");

        jTextField14.setText("jTextField1");

        jTextField15.setText("jTextField1");

        jTextField16.setText("jTextField1");

        javax.swing.GroupLayout subPanelNuevoTablaAutorLayout = new javax.swing.GroupLayout(subPanelNuevoTablaAutor);
        subPanelNuevoTablaAutor.setLayout(subPanelNuevoTablaAutorLayout);
        subPanelNuevoTablaAutorLayout.setHorizontalGroup(
            subPanelNuevoTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelNuevoTablaAutorLayout.createSequentialGroup()
                .addGroup(subPanelNuevoTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelNuevoTablaAutorLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel14))
                    .addGroup(subPanelNuevoTablaAutorLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(subPanelNuevoTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(subPanelNuevoTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(647, Short.MAX_VALUE))
        );
        subPanelNuevoTablaAutorLayout.setVerticalGroup(
            subPanelNuevoTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelNuevoTablaAutorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(subPanelNuevoTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelNuevoTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelNuevoTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelNuevoTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelNuevoTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelNuevoTablaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardLayoutTablaAutor.add(subPanelNuevoTablaAutor, "cardNuevoTablaAutor");

        javax.swing.GroupLayout panelAutoresLayout = new javax.swing.GroupLayout(panelAutores);
        panelAutores.setLayout(panelAutoresLayout);
        panelAutoresLayout.setHorizontalGroup(
            panelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autorBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autorNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autorEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autorModificar))
                .addContainerGap(1016, Short.MAX_VALUE))
            .addGroup(panelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAutoresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cardLayoutTablaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(panelAutoresLayout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(cardLayoutCamposAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        panelAutoresLayout.setVerticalGroup(
            panelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autorBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autorNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autorModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autorEliminar)
                .addContainerGap(483, Short.MAX_VALUE))
            .addGroup(panelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAutoresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cardLayoutCamposAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(cardLayoutTablaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 465, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Autores", panelAutores);

        javax.swing.GroupLayout panelEditorialesLayout = new javax.swing.GroupLayout(panelEditoriales);
        panelEditoriales.setLayout(panelEditorialesLayout);
        panelEditorialesLayout.setHorizontalGroup(
            panelEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1108, Short.MAX_VALUE)
        );
        panelEditorialesLayout.setVerticalGroup(
            panelEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Editoriales", panelEditoriales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton1ActionPerformed

        private void librosNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosNuevoActionPerformed
                // TODO add your handling code here:
		subPanelBuscarLibros.setVisible(false);
		subPanelNuevoLibros.setVisible(true);
		subPanelModificarLibros.setVisible(false);
		subPanelEliminarLibros.setVisible(false);
		((CardLayout) cardLayoutCamposLibros.getLayout()).show(cardLayoutCamposLibros, "cardNuevoLibros");
		subPanelBuscarTablaLibros.setVisible(false);
		subPanelNuevoTablaLibros.setVisible(true);
		subPanelModificarTablaLibros.setVisible(false);
		subPanelEliminarTablaLibros.setVisible(false);
		((CardLayout) cardLayoutTablaLibros.getLayout()).show(cardLayoutTablaLibros, "cardNuevoTablaLibros");
        }//GEN-LAST:event_librosNuevoActionPerformed

        private void librosBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosBuscarActionPerformed
                // TODO add your handling code here:
		subPanelBuscarLibros.setVisible(true);
		subPanelNuevoLibros.setVisible(false);
		subPanelModificarLibros.setVisible(false);
		subPanelEliminarLibros.setVisible(false);
		((CardLayout) cardLayoutCamposLibros.getLayout()).show(cardLayoutCamposLibros, "cardBuscarLibros");
		subPanelBuscarTablaLibros.setVisible(true);
		subPanelNuevoTablaLibros.setVisible(false);
		subPanelModificarTablaLibros.setVisible(false);
		subPanelEliminarTablaLibros.setVisible(false);
		((CardLayout) cardLayoutTablaLibros.getLayout()).show(cardLayoutTablaLibros, "cardBuscarTablaLibros");
        }//GEN-LAST:event_librosBuscarActionPerformed

        private void librosModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosModificarActionPerformed
                // TODO add your handling code here:
		subPanelBuscarLibros.setVisible(false);
		subPanelNuevoLibros.setVisible(false);
		subPanelModificarLibros.setVisible(true);
		subPanelEliminarLibros.setVisible(false);
		((CardLayout) cardLayoutCamposLibros.getLayout()).show(cardLayoutCamposLibros, "cardModificarLibros");
		subPanelBuscarTablaLibros.setVisible(false);
		subPanelNuevoTablaLibros.setVisible(false);
		subPanelModificarTablaLibros.setVisible(true);
		subPanelEliminarTablaLibros.setVisible(false);
		((CardLayout) cardLayoutTablaLibros.getLayout()).show(cardLayoutTablaLibros, "cardModificarTablaLibros");
        }//GEN-LAST:event_librosModificarActionPerformed

        private void librosEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosEliminarActionPerformed
                // TODO add your handling code here:
		subPanelBuscarLibros.setVisible(false);
		subPanelNuevoLibros.setVisible(false);
		subPanelModificarLibros.setVisible(false);
		subPanelEliminarLibros.setVisible(true);
		((CardLayout) cardLayoutCamposLibros.getLayout()).show(cardLayoutCamposLibros, "cardEliminarLibros");
		subPanelBuscarTablaLibros.setVisible(false);
		subPanelNuevoTablaLibros.setVisible(false);
		subPanelModificarTablaLibros.setVisible(false);
		subPanelEliminarTablaLibros.setVisible(true);
		((CardLayout) cardLayoutTablaLibros.getLayout()).show(cardLayoutTablaLibros, "cardEliminarTablaLibros");
        }//GEN-LAST:event_librosEliminarActionPerformed

        private void textoBuscarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBuscarLibrosActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_textoBuscarLibrosActionPerformed

        private void autorNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorNuevoActionPerformed
                // TODO add your handling code here:
		subPanelBuscarAutor.setVisible(false);
		subPanelNuevoAutor.setVisible(true);
		subPanelModificarAutor.setVisible(false);
		subPanelEliminarAutor.setVisible(false);
		((CardLayout) cardLayoutCamposAutor.getLayout()).show(cardLayoutCamposAutor, "cardNuevoAutor");
		subPanelBuscarTablaAutor.setVisible(false);
		subPanelNuevoTablaAutor.setVisible(true);
		subPanelModificarTablaAutor.setVisible(false);
		subPanelEliminarTablaAutor.setVisible(false);
		((CardLayout) cardLayoutTablaAutor.getLayout()).show(cardLayoutTablaAutor, "cardNuevoTablaAutor");
        }//GEN-LAST:event_autorNuevoActionPerformed

        private void autorBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorBuscarActionPerformed
                // TODO add your handling code here:
		subPanelBuscarAutor.setVisible(true);
		subPanelNuevoAutor.setVisible(false);
		subPanelModificarAutor.setVisible(false);
		subPanelEliminarAutor.setVisible(false);
		((CardLayout) cardLayoutCamposAutor.getLayout()).show(cardLayoutCamposAutor, "cardBuscarAutor");
		subPanelBuscarTablaAutor.setVisible(true);
		subPanelNuevoTablaAutor.setVisible(false);
		subPanelModificarTablaAutor.setVisible(false);
		subPanelEliminarTablaAutor.setVisible(false);
		((CardLayout) cardLayoutTablaAutor.getLayout()).show(cardLayoutTablaAutor, "cardBuscarTablaAutor");
        }//GEN-LAST:event_autorBuscarActionPerformed

        private void autorModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorModificarActionPerformed
                // TODO add your handling code here:
		subPanelBuscarAutor.setVisible(false);
		subPanelNuevoAutor.setVisible(false);
		subPanelModificarAutor.setVisible(true);
		subPanelEliminarAutor.setVisible(false);
		((CardLayout) cardLayoutCamposAutor.getLayout()).show(cardLayoutCamposAutor, "cardModificarAutor");
		subPanelBuscarTablaAutor.setVisible(false);
		subPanelNuevoTablaAutor.setVisible(false);
		subPanelModificarTablaAutor.setVisible(true);
		subPanelEliminarTablaAutor.setVisible(false);
		((CardLayout) cardLayoutTablaAutor.getLayout()).show(cardLayoutTablaAutor, "cardModificarTablaAutor");
        }//GEN-LAST:event_autorModificarActionPerformed

        private void autorEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorEliminarActionPerformed
                // TODO add your handling code here:
		subPanelBuscarAutor.setVisible(false);
		subPanelNuevoAutor.setVisible(false);
		subPanelModificarAutor.setVisible(false);
		subPanelEliminarAutor.setVisible(true);
		((CardLayout) cardLayoutCamposAutor.getLayout()).show(cardLayoutCamposAutor, "cardEliminarAutor");
		subPanelBuscarTablaAutor.setVisible(false);
		subPanelNuevoTablaAutor.setVisible(false);
		subPanelModificarTablaAutor.setVisible(false);
		subPanelEliminarTablaAutor.setVisible(true);
		((CardLayout) cardLayoutTablaAutor.getLayout()).show(cardLayoutTablaAutor, "cardEliminarTablaAutor");
        }//GEN-LAST:event_autorEliminarActionPerformed

        private void textoBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBuscarAutorActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_textoBuscarAutorActionPerformed

        private void radioApellidoBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioApellidoBuscarAutorActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_radioApellidoBuscarAutorActionPerformed

        private void buttonBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarAutorActionPerformed
                String textoBuscar = textoBuscarAutor.getText();
				if (textoBuscar.length() > 0) {
					AutoresDAO dbAutores = new AutoresDAO();

					try {
						ArrayList<Autor> autores = dbAutores.searchAutor(textoBuscar, 
															buttonGroupBuscarAutor
																	.getSelection()
																	.getActionCommand());
						fillTableBuscarAutor(autores);
					}
					catch (Exception e){ // acá puede haber un error
						;
					}
				}
        }//GEN-LAST:event_buttonBuscarAutorActionPerformed

		
	private void fillTableBuscarAutor (ArrayList<Autor> autores) {
		
		int columnsAutoresTable = 4;
		Object forTable[][] = new Object[autores.size()][columnsAutoresTable];
		
		for (int i=0; i<autores.size(); i++) {
			forTable[i][0] = autores.get(i).getApellido();
			forTable[i][1] = autores.get(i).getNombre();
			forTable[i][2] = autores.get(i).getNacionalidad();
			forTable[i][3] = autores.get(i).getFechaNacimiento();
		}
		
		tablaBuscarAutor.setModel(new javax.swing.table.DefaultTableModel(
            forTable,
            new String [] {
                "Apellido", "Nombre", "Nacionalidad", "Fecha de Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
	}
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autorBuscar;
    private javax.swing.JButton autorEliminar;
    private javax.swing.JButton autorModificar;
    private javax.swing.JButton autorNuevo;
    private javax.swing.JButton buttonBuscarAutor;
    private javax.swing.JButton buttonBuscarLibros;
    private javax.swing.ButtonGroup buttonGroupBuscarAutor;
    private javax.swing.ButtonGroup buttonGroupBuscarLibros;
    private javax.swing.JPanel cardLayoutCamposAutor;
    private javax.swing.JPanel cardLayoutCamposLibros;
    private javax.swing.JPanel cardLayoutTablaAutor;
    private javax.swing.JPanel cardLayoutTablaLibros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton librosBuscar;
    private javax.swing.JButton librosEliminar;
    private javax.swing.JButton librosModificar;
    private javax.swing.JButton librosNuevo;
    private javax.swing.JPanel panelAfiliados;
    private javax.swing.JPanel panelAutores;
    private javax.swing.JPanel panelEditoriales;
    private javax.swing.JPanel panelLibros;
    private javax.swing.JPanel panelPrestamos;
    private javax.swing.JRadioButton radioApellidoBuscarAutor;
    private javax.swing.JRadioButton radioNacionalidadBuscarAutor;
    private javax.swing.JRadioButton radioNombreBuscarAutor;
    private javax.swing.JPanel subPanelBuscarAutor;
    private javax.swing.JPanel subPanelBuscarLibros;
    private javax.swing.JPanel subPanelBuscarTablaAutor;
    private javax.swing.JPanel subPanelBuscarTablaLibros;
    private javax.swing.JPanel subPanelEliminarAutor;
    private javax.swing.JPanel subPanelEliminarLibros;
    private javax.swing.JPanel subPanelEliminarTablaAutor;
    private javax.swing.JPanel subPanelEliminarTablaLibros;
    private javax.swing.JPanel subPanelModificarAutor;
    private javax.swing.JPanel subPanelModificarLibros;
    private javax.swing.JPanel subPanelModificarTablaAutor;
    private javax.swing.JPanel subPanelModificarTablaLibros;
    private javax.swing.JPanel subPanelNuevoAutor;
    private javax.swing.JPanel subPanelNuevoLibros;
    private javax.swing.JPanel subPanelNuevoTablaAutor;
    private javax.swing.JPanel subPanelNuevoTablaLibros;
    private javax.swing.JTable tablaBuscarAutor;
    private javax.swing.JTextField textoBuscarAutor;
    private javax.swing.JTextField textoBuscarLibros;
    // End of variables declaration//GEN-END:variables
}
